version: "3.9"

services:

  password_generator:  
    container_name: password_generator 
    build:
      context: .
      dockerfile: ./passwordGen/Dockerfile
    volumes:    
      - .:/app  

  # process_monitor:  
  #   container_name: process_monitor 
  #   build:
  #     context: .
  #     dockerfile: ./processMonitor/Dockerfile
  #   volumes:    
  #     - .:/app

  contact_book:  
    container_name: contact_book 
    build:
      context: .
      dockerfile: ./contactBook/Dockerfile
    volumes:    
      - .:/app  


volumes:
  app: